// Generated by Bisonc++ V6.01.00 on Thu, 23 Apr 2020 11:13:10 +0800

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved__::UNDETERMINED__, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok__
// which is applied. In this errTok__ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved__
    {
        UNDETERMINED__   = -2,
        EOF__            = -1,
        errTok__         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    enum StateTransition
    {
        ACCEPT__   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {284, 1}, // 1: program ->  declaration_list
     {285, 2}, // 2: declaration_list ->  declaration_list declaration
     {285, 1}, // 3: declaration_list ->  declaration
     {286, 1}, // 4: declaration ->  var_declaration
     {286, 1}, // 5: declaration ->  fun_declaration
     {287, 3}, // 6: var_declaration (ID) ->  type_specifier ID SEMICOLON
     {287, 6}, // 7: var_declaration (ID) ->  type_specifier ID LEFTS NUM RIGHTS SEMICOLON
     {289, 1}, // 8: type_specifier (INT) ->  INT
     {289, 1}, // 9: type_specifier (VOID) ->  VOID
     {288, 6}, // 10: fun_declaration (ID) ->  type_specifier ID LEFTP params RIGHTP compound_stmt
     {290, 1}, // 11: params ->  param_list
     {290, 1}, // 12: params (VOID) ->  VOID
     {292, 3}, // 13: param_list (COMMA) ->  param_list COMMA param
     {292, 1}, // 14: param_list ->  param
     {293, 2}, // 15: param (ID) ->  type_specifier ID
     {293, 4}, // 16: param (ID) ->  type_specifier ID LEFTS RIGHTS
     {291, 4}, // 17: compound_stmt (LEFTB) ->  LEFTB local_declarations statement_list RIGHTB
     {294, 2}, // 18: local_declarations ->  local_declarations var_declaration
     {294, 1}, // 19: local_declarations ->  empty
     {295, 2}, // 20: statement_list ->  statement_list statement
     {295, 1}, // 21: statement_list ->  empty
     {297, 1}, // 22: statement ->  expression_stmt
     {297, 1}, // 23: statement ->  compound_stmt
     {297, 1}, // 24: statement ->  selection_stmt
     {297, 1}, // 25: statement ->  iteration_stmt
     {297, 1}, // 26: statement ->  return_stmt
     {298, 2}, // 27: expression_stmt (SEMICOLON) ->  expression SEMICOLON
     {298, 1}, // 28: expression_stmt (SEMICOLON) ->  SEMICOLON
     {299, 5}, // 29: selection_stmt (IF) ->  IF LEFTP expression RIGHTP statement
     {299, 7}, // 30: selection_stmt (IF) ->  IF LEFTP expression RIGHTP statement ELSE statement
     {300, 5}, // 31: iteration_stmt (WHILE) ->  WHILE LEFTP expression RIGHTP statement
     {301, 2}, // 32: return_stmt (RETURN) ->  RETURN SEMICOLON
     {301, 3}, // 33: return_stmt (RETURN) ->  RETURN expression SEMICOLON
     {302, 3}, // 34: expression (ASSIGN) ->  var ASSIGN expression
     {302, 1}, // 35: expression ->  simple_expression
     {303, 1}, // 36: var (ID) ->  ID
     {303, 4}, // 37: var (ID) ->  ID LEFTS expression RIGHTS
     {304, 3}, // 38: simple_expression ->  additive_expression relop additive_expression
     {304, 1}, // 39: simple_expression ->  additive_expression
     {306, 1}, // 40: relop (LE) ->  LE
     {306, 1}, // 41: relop (LT) ->  LT
     {306, 1}, // 42: relop (GT) ->  GT
     {306, 1}, // 43: relop (GE) ->  GE
     {306, 1}, // 44: relop (EQ) ->  EQ
     {306, 1}, // 45: relop (NE) ->  NE
     {305, 3}, // 46: additive_expression ->  additive_expression addop term
     {305, 1}, // 47: additive_expression ->  term
     {307, 1}, // 48: addop (ADD) ->  ADD
     {307, 1}, // 49: addop (SUB) ->  SUB
     {308, 3}, // 50: term ->  term mulop factor
     {308, 1}, // 51: term ->  factor
     {309, 1}, // 52: mulop (MUL) ->  MUL
     {309, 1}, // 53: mulop (DIV) ->  DIV
     {310, 3}, // 54: factor (LEFTP) ->  LEFTP expression RIGHTP
     {310, 1}, // 55: factor ->  var
     {310, 1}, // 56: factor ->  call
     {310, 1}, // 57: factor (NUM) ->  NUM
     {311, 4}, // 58: call (ID) ->  ID LEFTP args RIGHTP
     {312, 1}, // 59: args ->  arg_list
     {312, 1}, // 60: args ->  empty
     {313, 3}, // 61: arg_list (COMMA) ->  arg_list COMMA expression
     {313, 1}, // 62: arg_list ->  expression
     {296, 0}, // 63: empty ->  <empty>
     {314, 1}, // 64: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 9} },                    
    { {       284}, { 1} }, // program         
    { {       285}, { 2} }, // declaration_list
    { {       286}, { 3} }, // declaration     
    { {       287}, { 4} }, // var_declaration 
    { {       288}, { 5} }, // fun_declaration 
    { {       289}, { 6} }, // type_specifier  
    { {       260}, { 7} }, // INT             
    { {       261}, { 8} }, // VOID            
    { {         0}, { 0} },                    
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {        2} }, 
    { {     EOF__}, { ACCEPT__} }, 
    { {         0}, {        0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  7} },                   
    { {     286}, {  9} }, // declaration    
    { {     287}, {  4} }, // var_declaration
    { {     288}, {  5} }, // fun_declaration
    { {     289}, {  6} }, // type_specifier 
    { {     260}, {  7} }, // INT            
    { {     261}, {  8} }, // VOID           
    { {       0}, { -1} },                   
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       263}, { 10} }, // ID
    { {         0}, {  0} },      
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  4} },             
    { {       272}, { 11} }, // SEMICOLON
    { {       267}, { 12} }, // LEFTS    
    { {       265}, { 13} }, // LEFTP    
    { {         0}, {  0} },             
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       264}, { 14} }, // NUM
    { {         0}, {  0} },       
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  7} },                  
    { {       290}, { 15} }, // params        
    { {       292}, { 16} }, // param_list    
    { {       261}, { 17} }, // VOID          
    { {       293}, { 18} }, // param         
    { {       289}, { 19} }, // type_specifier
    { {       260}, {  7} }, // INT           
    { {         0}, {  0} },                  
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       268}, { 20} }, // RIGHTS
    { {         0}, {  0} },          
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       266}, { 21} }, // RIGHTP
    { {         0}, {  0} },          
};

SR__ s_16[] =
{
    { { REQ_DEF}, {   2} },         
    { {     271}, {  22} }, // COMMA
    { {       0}, { -11} },         
};

SR__ s_17[] =
{
    { { REQ_DEF}, {   2} },          
    { {     266}, { -12} }, // RIGHTP
    { {       0}, {  -9} },          
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       263}, { 23} }, // ID
    { {         0}, {  0} },      
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       272}, { 24} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },                 
    { {       291}, { 25} }, // compound_stmt
    { {       269}, { 26} }, // LEFTB        
    { {         0}, {  0} },                 
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  5} },                  
    { {       293}, { 27} }, // param         
    { {       289}, { 19} }, // type_specifier
    { {       260}, {  7} }, // INT           
    { {       261}, {  8} }, // VOID          
    { {         0}, {  0} },                  
};

SR__ s_23[] =
{
    { { REQ_DEF}, {   2} },         
    { {     267}, {  28} }, // LEFTS
    { {       0}, { -15} },         
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   3} },                      
    { {     294}, {  29} }, // local_declarations
    { {     296}, {  30} }, // empty             
    { {       0}, { -63} },                      
};

SR__ s_27[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       268}, { 31} }, // RIGHTS
    { {         0}, {  0} },          
};

SR__ s_29[] =
{
    { { REQ_DEF}, {   7} },                   
    { {     295}, {  32} }, // statement_list 
    { {     287}, {  33} }, // var_declaration
    { {     296}, {  34} }, // empty          
    { {     289}, {  35} }, // type_specifier 
    { {     260}, {   7} }, // INT            
    { {     261}, {   8} }, // VOID           
    { {       0}, { -63} },                   
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 23} },                       
    { {       270}, { 36} }, // RIGHTB             
    { {       297}, { 37} }, // statement          
    { {       298}, { 38} }, // expression_stmt    
    { {       291}, { 39} }, // compound_stmt      
    { {       299}, { 40} }, // selection_stmt     
    { {       300}, { 41} }, // iteration_stmt     
    { {       301}, { 42} }, // return_stmt        
    { {       302}, { 43} }, // expression         
    { {       272}, { 44} }, // SEMICOLON          
    { {       269}, { 26} }, // LEFTB              
    { {       258}, { 45} }, // IF                 
    { {       262}, { 46} }, // WHILE              
    { {       259}, { 47} }, // RETURN             
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       263}, { 57} }, // ID
    { {         0}, {  0} },      
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       272}, { 58} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_44[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       265}, { 59} }, // LEFTP
    { {         0}, {  0} },         
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       265}, { 60} }, // LEFTP
    { {         0}, {  0} },         
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 12} },                       
    { {       272}, { 61} }, // SEMICOLON          
    { {       302}, { 62} }, // expression         
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_48[] =
{
    { { REQ_DEF}, {   2} },          
    { {     277}, {  63} }, // ASSIGN
    { {       0}, { -55} },          
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   3} },         
    { {     267}, {  64} }, // LEFTS
    { {     265}, {  65} }, // LEFTP
    { {       0}, { -36} },         
};

SR__ s_51[] =
{
    { { REQ_DEF}, {  11} },         
    { {     306}, {  66} }, // relop
    { {     307}, {  67} }, // addop
    { {     279}, {  68} }, // LE   
    { {     278}, {  69} }, // LT   
    { {     280}, {  70} }, // GT   
    { {     281}, {  71} }, // GE   
    { {     282}, {  72} }, // EQ   
    { {     283}, {  73} }, // NE   
    { {     273}, {  74} }, // ADD  
    { {     274}, {  75} }, // SUB  
    { {       0}, { -39} },         
};

SR__ s_52[] =
{
    { { REQ_DEF}, {   4} },         
    { {     309}, {  76} }, // mulop
    { {     275}, {  77} }, // MUL  
    { {     276}, {  78} }, // DIV  
    { {       0}, { -47} },         
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, { 11} },                       
    { {       302}, { 79} }, // expression         
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -56} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -57} }, 
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       272}, { 11} }, // SEMICOLON
    { {       267}, { 12} }, // LEFTS    
    { {         0}, {  0} },             
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 11} },                       
    { {       302}, { 80} }, // expression         
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 11} },                       
    { {       302}, { 81} }, // expression         
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       272}, { 82} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 11} },                       
    { {       302}, { 83} }, // expression         
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 11} },                       
    { {       302}, { 84} }, // expression         
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_65[] =
{
    { { REQ_DEF}, {  14} },                       
    { {     312}, {  85} }, // args               
    { {     313}, {  86} }, // arg_list           
    { {     296}, {  87} }, // empty              
    { {     302}, {  88} }, // expression         
    { {     303}, {  48} }, // var                
    { {     304}, {  49} }, // simple_expression  
    { {     263}, {  50} }, // ID                 
    { {     305}, {  51} }, // additive_expression
    { {     308}, {  52} }, // term               
    { {     310}, {  53} }, // factor             
    { {     265}, {  54} }, // LEFTP              
    { {     311}, {  55} }, // call               
    { {     264}, {  56} }, // NUM                
    { {       0}, { -63} },                       
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  9} },                       
    { {       305}, { 89} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       303}, { 90} }, // var                
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {       263}, { 50} }, // ID                 
    { {         0}, {  0} },                       
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  8} },          
    { {       308}, { 91} }, // term  
    { {       310}, { 53} }, // factor
    { {       265}, { 54} }, // LEFTP 
    { {       303}, { 90} }, // var   
    { {       311}, { 55} }, // call  
    { {       264}, { 56} }, // NUM   
    { {       263}, { 50} }, // ID    
    { {         0}, {  0} },          
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  7} },          
    { {       310}, { 92} }, // factor
    { {       265}, { 54} }, // LEFTP 
    { {       303}, { 90} }, // var   
    { {       311}, { 55} }, // call  
    { {       264}, { 56} }, // NUM   
    { {       263}, { 50} }, // ID    
    { {         0}, {  0} },          
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       266}, { 93} }, // RIGHTP
    { {         0}, {  0} },          
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       266}, { 94} }, // RIGHTP
    { {         0}, {  0} },          
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       266}, { 95} }, // RIGHTP
    { {         0}, {  0} },          
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       268}, { 96} }, // RIGHTS
    { {         0}, {  0} },          
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       266}, { 97} }, // RIGHTP
    { {         0}, {  0} },          
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   2} },         
    { {     271}, {  98} }, // COMMA
    { {       0}, { -59} },         
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -60} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -62} }, 
};

SR__ s_89[] =
{
    { { REQ_DEF}, {   4} },         
    { {     307}, {  67} }, // addop
    { {     273}, {  74} }, // ADD  
    { {     274}, {  75} }, // SUB  
    { {       0}, { -38} },         
};

SR__ s_90[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};

SR__ s_91[] =
{
    { { REQ_DEF}, {   4} },         
    { {     309}, {  76} }, // mulop
    { {     275}, {  77} }, // MUL  
    { {     276}, {  78} }, // DIV  
    { {       0}, { -46} },         
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, { 22} },                       
    { {       297}, { 99} }, // statement          
    { {       298}, { 38} }, // expression_stmt    
    { {       291}, { 39} }, // compound_stmt      
    { {       299}, { 40} }, // selection_stmt     
    { {       300}, { 41} }, // iteration_stmt     
    { {       301}, { 42} }, // return_stmt        
    { {       302}, { 43} }, // expression         
    { {       272}, { 44} }, // SEMICOLON          
    { {       269}, { 26} }, // LEFTB              
    { {       258}, { 45} }, // IF                 
    { {       262}, { 46} }, // WHILE              
    { {       259}, { 47} }, // RETURN             
    { {       303}, { 48} }, // var                
    { {       304}, { 49} }, // simple_expression  
    { {       263}, { 50} }, // ID                 
    { {       305}, { 51} }, // additive_expression
    { {       308}, { 52} }, // term               
    { {       310}, { 53} }, // factor             
    { {       265}, { 54} }, // LEFTP              
    { {       311}, { 55} }, // call               
    { {       264}, { 56} }, // NUM                
    { {         0}, {  0} },                       
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {       297}, { 100} }, // statement          
    { {       298}, {  38} }, // expression_stmt    
    { {       291}, {  39} }, // compound_stmt      
    { {       299}, {  40} }, // selection_stmt     
    { {       300}, {  41} }, // iteration_stmt     
    { {       301}, {  42} }, // return_stmt        
    { {       302}, {  43} }, // expression         
    { {       272}, {  44} }, // SEMICOLON          
    { {       269}, {  26} }, // LEFTB              
    { {       258}, {  45} }, // IF                 
    { {       262}, {  46} }, // WHILE              
    { {       259}, {  47} }, // RETURN             
    { {       303}, {  48} }, // var                
    { {       304}, {  49} }, // simple_expression  
    { {       263}, {  50} }, // ID                 
    { {       305}, {  51} }, // additive_expression
    { {       308}, {  52} }, // term               
    { {       310}, {  53} }, // factor             
    { {       265}, {  54} }, // LEFTP              
    { {       311}, {  55} }, // call               
    { {       264}, {  56} }, // NUM                
    { {         0}, {   0} },                       
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -58} }, 
};

SR__ s_98[] =
{
    { { REQ_TOKEN}, {  11} },                       
    { {       302}, { 101} }, // expression         
    { {       303}, {  48} }, // var                
    { {       304}, {  49} }, // simple_expression  
    { {       263}, {  50} }, // ID                 
    { {       305}, {  51} }, // additive_expression
    { {       308}, {  52} }, // term               
    { {       310}, {  53} }, // factor             
    { {       265}, {  54} }, // LEFTP              
    { {       311}, {  55} }, // call               
    { {       264}, {  56} }, // NUM                
    { {         0}, {   0} },                       
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   2} },        
    { {     257}, { 102} }, // ELSE
    { {       0}, { -29} },        
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -61} }, 
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  22} },                       
    { {       297}, { 103} }, // statement          
    { {       298}, {  38} }, // expression_stmt    
    { {       291}, {  39} }, // compound_stmt      
    { {       299}, {  40} }, // selection_stmt     
    { {       300}, {  41} }, // iteration_stmt     
    { {       301}, {  42} }, // return_stmt        
    { {       302}, {  43} }, // expression         
    { {       272}, {  44} }, // SEMICOLON          
    { {       269}, {  26} }, // LEFTB              
    { {       258}, {  45} }, // IF                 
    { {       262}, {  46} }, // WHILE              
    { {       259}, {  47} }, // RETURN             
    { {       303}, {  48} }, // var                
    { {       304}, {  49} }, // simple_expression  
    { {       263}, {  50} }, // ID                 
    { {       305}, {  51} }, // additive_expression
    { {       308}, {  52} }, // term               
    { {       310}, {  53} }, // factor             
    { {       265}, {  54} }, // LEFTP              
    { {       311}, {  55} }, // call               
    { {       264}, {  56} }, // NUM                
    { {         0}, {   0} },                       
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved__::UNDETERMINED__),
    // $insert baseclasscode
    d_requiredTokens__(0)
{
}

// base/clearin
void ParserBase::clearin__()
{
    d_nErrors__ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved__::UNDETERMINED__;
    d_next = TokenPair{ Reserved__::UNDETERMINED__, STYPE__{} };
    d_recovery = false;
    d_acceptedTokens__ = d_requiredTokens__;
    d_val__ = STYPE__{};

    push__(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

// base/lex
void ParserBase::lex__(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved__::EOF__;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup__() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR__ const *sr = s_state[d_state];
    SR__ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken__()
{
    d_token = d_next.first;
    d_val__ = std::move(d_next.second);

    d_next.first = Reserved__::UNDETERMINED__;
}

// base/push
void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize__() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val__) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken__(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val__) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken__()
{
    if (d_token != Reserved__::UNDETERMINED__)
        pushToken__(d_token);
}

// base/reduce
void ParserBase::reduce__(int rule)
{
    PI__ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop__(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift__(int action)
{
    push__(action);
    popToken__();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens__ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery__()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken__(Reserved__::errTok__);      // specify errTok__ as next token
    push__(lookup__());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top__() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery__()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle__ for details.

    startRecovery__();
}

// derived/executeaction
void Parser::executeAction__(int production)
try
{
    if (token__() != Reserved__::UNDETERMINED__)
        pushToken__(token__());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         std::cout << "成功" << endl;
         }
        break;

        case 2:
        {
            d_val__ = vs__(-1);
        }
        break;

        case 3:
        {
            d_val__ = vs__(0);
        }
        break;

        case 4:
        {
            d_val__ = vs__(0);
        }
        break;

        case 5:
        {
            d_val__ = vs__(0);
        }
        break;

        case 6:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 7:
        {
            d_val__ = vs__(-5);
        }
        break;

        case 8:
        {
            d_val__ = vs__(0);
        }
        break;

        case 9:
        {
            d_val__ = vs__(0);
        }
        break;

        case 10:
        {
            d_val__ = vs__(-5);
        }
        break;

        case 11:
        {
            d_val__ = vs__(0);
        }
        break;

        case 12:
        {
            d_val__ = vs__(0);
        }
        break;

        case 13:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 14:
        {
            d_val__ = vs__(0);
        }
        break;

        case 15:
        {
            d_val__ = vs__(-1);
        }
        break;

        case 16:
        {
            d_val__ = vs__(-3);
        }
        break;

        case 17:
        {
            d_val__ = vs__(-3);
        }
        break;

        case 18:
        {
            d_val__ = vs__(-1);
        }
        break;

        case 19:
        {
            d_val__ = vs__(0);
        }
        break;

        case 20:
        {
            d_val__ = vs__(-1);
        }
        break;

        case 21:
        {
            d_val__ = vs__(0);
        }
        break;

        case 22:
        {
            d_val__ = vs__(0);
        }
        break;

        case 23:
        {
            d_val__ = vs__(0);
        }
        break;

        case 24:
        {
            d_val__ = vs__(0);
        }
        break;

        case 25:
        {
            d_val__ = vs__(0);
        }
        break;

        case 26:
        {
            d_val__ = vs__(0);
        }
        break;

        case 27:
        {
            d_val__ = vs__(-1);
        }
        break;

        case 28:
        {
            d_val__ = vs__(0);
        }
        break;

        case 29:
        {
            d_val__ = vs__(-4);
        }
        break;

        case 30:
        {
            d_val__ = vs__(-6);
        }
        break;

        case 31:
        {
            d_val__ = vs__(-4);
        }
        break;

        case 32:
        {
            d_val__ = vs__(-1);
        }
        break;

        case 33:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 34:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 35:
        {
            d_val__ = vs__(0);
        }
        break;

        case 36:
        {
            d_val__ = vs__(0);
        }
        break;

        case 37:
        {
            d_val__ = vs__(-3);
        }
        break;

        case 38:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 39:
        {
            d_val__ = vs__(0);
        }
        break;

        case 40:
        {
            d_val__ = vs__(0);
        }
        break;

        case 41:
        {
            d_val__ = vs__(0);
        }
        break;

        case 42:
        {
            d_val__ = vs__(0);
        }
        break;

        case 43:
        {
            d_val__ = vs__(0);
        }
        break;

        case 44:
        {
            d_val__ = vs__(0);
        }
        break;

        case 45:
        {
            d_val__ = vs__(0);
        }
        break;

        case 46:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 47:
        {
            d_val__ = vs__(0);
        }
        break;

        case 48:
        {
            d_val__ = vs__(0);
        }
        break;

        case 49:
        {
            d_val__ = vs__(0);
        }
        break;

        case 50:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 51:
        {
            d_val__ = vs__(0);
        }
        break;

        case 52:
        {
            d_val__ = vs__(0);
        }
        break;

        case 53:
        {
            d_val__ = vs__(0);
        }
        break;

        case 54:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 55:
        {
            d_val__ = vs__(0);
        }
        break;

        case 56:
        {
            d_val__ = vs__(0);
        }
        break;

        case 57:
        {
            d_val__ = vs__(0);
        }
        break;

        case 58:
        {
            d_val__ = vs__(-3);
        }
        break;

        case 59:
        {
            d_val__ = vs__(0);
        }
        break;

        case 60:
        {
            d_val__ = vs__(0);
        }
        break;

        case 61:
        {
            d_val__ = vs__(-2);
        }
        break;

        case 62:
        {
            d_val__ = vs__(0);
        }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle__()
try
{
    if (s_state[state__()]->d_type & REQ_TOKEN)
        nextToken__();              // obtain next token


    int action = lookup__();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift__(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery__())
            redoToken__();
        else
            executeAction__(-action);
                                            // next token is the rule's LHS
        reduce__(-action); 
        return;
    }

    if (recovery__())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery__)
{
    if (not recovery__())
        errorRecovery__();
    else
    {
        if (token__() == Reserved__::EOF__)
            ABORT();
        popToken__();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken__()
{ 
    // If d_token is Reserved__::UNDETERMINED__ then if savedToken__() is
    // Reserved__::UNDETERMINED__ another token is obtained from lex(). Then
    // savedToken__() is assigned to d_token.

                                    // no need for a token: got one already
    if (token__() != Reserved__::UNDETERMINED__) 
    {
        return;                             
    }

    if (savedToken__() != Reserved__::UNDETERMINED__)
    {
        popToken__();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;       // accept another token (see
                                    // errorRecover())
        lex__(lex());
        print__();
    }
    print();
}

// derived/print
void Parser::print__()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin__.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin__();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle__();
    }
}
catch (Return__ retValue)
{
    return retValue or d_nErrors__;
}


// derived/tail


